apiVersion: apps/v1
kind: Deployment
metadata:
    name: imgproc-client
spec:
    replicas: 1
    selector:
        matchLabels:
            app: imageProcessing
            tier: client
    template:
        metadata:
            labels:
                app: imageProcessing
                tier: client
        spec:          
            containers:
            - name: imgproc-client
              image: wangso/imgproc-client:V1
              imagePullPolicy: Always
              env:
                - name: server
                  value: "Your_Server_Ingress_Name"	
              resources:
                limits:
                  memory: 2000Mi
                  cpu: 2
                requests:
                  memory: 1000Mi
                  cpu: 1
              volumeMounts:
              - mountPath: /ImageProcessingWebServices/output/client
                name: mizzoucerivolume
            volumes:
            - name: mizzoucerivolume
              persistentVolumeClaim:
                claimName: mizzoucerivolume  
            restartPolicy: Always

      
