apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod-example
spec:
  containers:
  - name: gpu-container
    image: wangso/imgproc-server:gpu
    command: ["sleep", "infinity"]
    imagePullPolicy: Always
    resources:
      limits:
        nvidia.com/gpu: 1
